### ISSUE TITLE
TrackMe bug report - Windows based deployment reports ERROR JSON reply had no "payload" value in rest calls

### ISSUE THREAD

**Issue by horacio-basilio** [guilhemmarchand/trackme#362]
Hello how are you?

I have a problem when I try to adjust some lag time of events or ingests.

It gives the error:

"Sorry but it looks like an error occurred while attempting to perform the KVstore collection update.

You might not have the permission to write to the collection, or an unexpected failure was encountered.

The server returned the following error message:

server response: <? xml version = "1.0" encoding = "UTF-8"?> <response> <messages> <msg type = "ERROR"> JSON reply had no "payload" value </msg> </messages> </response> - http response: JSON reply had no "payload" value "

![image](https://user-images.githubusercontent.com/88854639/129254943-63d9cb73-d854-4e7d-8b4d-0504a9411d32.png)

What is the problem?
My Splunk is installed on a Windows Server.

Greetings

Horacio

**Comment by guilhemmarchand** [comment]
Hi @horacio-basilio !
Thanks for opening this issue, hope you are doing well.
I was reported earlier similar issues on Windows.

This indeed is an unknown issue I will look into, that is specific Windows based deployments.

I will look into this issue as soon as possible.

Guilhem

**Comment by guilhemmarchand** [comment]
The issue seems to stand at the level of the call of a Python library in Windows context:

```
08-16-2021 10:10:11.625 +0000 WARN PersistentScript [7888 PersistentScriptIo] - Process {"C:\Program Files\Splunk\bin\Python3.exe" "C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: exited with code 1
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: import imp
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: Traceback (most recent call last):
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: File "C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py", line 114, in <module>
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: h.run()
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\persistconn\packet.py", line 191, in run
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: self.handle_packet(in_packet)
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\persistconn\handle_loop.py", line 36, in handle_packet
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: self._current_handler = self.load(in_packet.command, in_packet.command_arg, in_packet.allow_stream())
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: File "C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py", line 22, in load
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: class_and_meths = self._get_class_and_methods(command[0], stream_allowed)
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: File "C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py", line 31, in _get_class_and_methods
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: meths = self._cached_load_file(filename)
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: File "C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py", line 42, in _cached_load_file
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: rv = PersistentServerConnectionApplicationServer._load_file(filename)
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: File "C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py", line 57, in _load_file
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: m = imp.load_module(munged_name, filehandle, filename, data)
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: File "C:\Program Files\Splunk\Python-3.7\lib\imp.py", line 234, in load_module
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: return load_source(name, filename, file)
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: File "C:\Program Files\Splunk\Python-3.7\lib\imp.py", line 171, in load_source
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: module = _load(spec)
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: File "<frozen importlib._bootstrap>", line 696, in _load
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: File "<frozen importlib._bootstrap_external>", line 728, in exec_module
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: File "C:\Program Files\Splunk\etc\apps\trackme\bin\trackme_rest_handler_ack.py", line 13, in <module>
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: import rest_handler
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: File "C:\Program Files\Splunk\bin\rest_handler.py", line 58, in <module>
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: assert(len(sys.argv) > 1)
"C:\Program Files\Splunk\Python-3.7\Lib\site-packages\splunk\persistconn\appserver.py"}: AssertionError
08-16-2021 10:10:19.940 +0000 WARN LocalAppsAdminHandler [3828 TcpChannelThread] - Using deprecated capabilities for write: admin_all_objects or edit_local_apps. See enable_install_apps in limits.conf
```

Issue is under investigations.

**Comment by guilhemmarchand** [comment]
It turns out that issues on Windows plateforms when performing rest calls are due to a conflict at the Python level with a file named rest_handler.py provided OOTB in Windows, while TrackMe has its own library named the same:

```
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\trackme\bin\trackme_rest_handler_ack.py", line 13, in <module>
    import rest_handler
  File "C:\Program Files\Splunk\bin\rest_handler.py", line 58, in <module>
    assert(len(sys.argv) > 1)
AssertionError
```

For some reasons, this only impacts Windows plateforms.
